apiVersion: batch/v1
kind: Job
metadata:
  name: schema-publisher-job
  namespace: kafka
spec:
  template:
    spec:
      containers:
        - name: schema-publisher
          image: python:3.9-slim
          command:
            - /bin/sh
            - -c
            - pip install "confluent-kafka[protobuf]" && python /scripts/hello.py
          volumeMounts:
            - name: script-volume
              mountPath: /scripts
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: script-volume
          configMap:
            name: schema-publisher-config
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 3
