apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-publisher-config
  namespace: kafka
data:
  hello.py: |
    #!/usr/bin/env python3
    import os
    import sys

    def main():
        print("Hello from Python!")
        print(f"Running in namespace: {os.getenv('POD_NAMESPACE', 'unknown')}")
        print("Script executed successfully!")

    if __name__ == "__main__":
        main()
