{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.kafka.name }}-kafka-pdb
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      strimzi.io/cluster: {{ .Values.kafka.name }}
      strimzi.io/kind: Kafka
      strimzi.io/name: {{ .Values.kafka.name }}-kafka
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.kafka.name }}-zookeeper-pdb
  labels:
    {{- include "kafka-cluster.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      strimzi.io/cluster: {{ .Values.kafka.name }}
      strimzi.io/kind: Kafka
      strimzi.io/name: {{ .Values.kafka.name }}-zookeeper
{{- end }}