apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluent-schema-registry
  labels:
    app: confluent-schema-registry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: confluent-schema-registry
  template:
    metadata:
      labels:
        app: confluent-schema-registry
    spec:
      containers:
      - name: schema-registry
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: {{ .Values.schemaRegistry.hostname }}
        - name: SCHEMA_REGISTRY_LISTENERS
          value: {{ .Values.schemaRegistry.listeners }}
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: {{ .Values.kafka.bootstrapServers }}
        - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
          value: {{ .Values.schemaRegistry.kafkastoreTopicName }}
        - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC_REPLICATION_FACTOR
          value: {{ .Values.schemaRegistry.kafkastoreTopicReplicationFactor | quote }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}