apiVersion: v1
kind: Service
metadata:
  name: confluent-schema-registry
  labels:
    app: confluent-schema-registry
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: confluent-schema-registry