apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: postgres
data:
  # Scripts run in alphabetical order
  # 01-create-database.sql: |
  #   -- Create the testing_playground_service database
  #   CREATE DATABASE testing_playground_service;

  02-create-tables.sql: |
    -- Connect to testing_playground_service database and create tables
    \c testing_playground_service

    CREATE TABLE IF NOT EXISTS idempotent_action (
        key             TEXT        NOT NULL,
        type            TEXT        NOT NULL,
        client          TEXT        NOT NULL,
        created_at      TIMESTAMP   NOT NULL,
        last_run_at     TIMESTAMP,
        completed_at    TIMESTAMP,
        result          BYTEA,
        result_type     VARCHAR(255),

        PRIMARY KEY(key, type, client)
    );

    CREATE INDEX IF NOT EXISTS IDX_IDEMPOTENT_ACTION_CREATED_AT ON idempotent_action (created_at ASC);

    CREATE TABLE IF NOT EXISTS idempotence4j_scheduled_tasks (
        task_name               TEXT                        NOT NULL,
        task_instance           TEXT                        NOT NULL,
        task_data               BYTEA,
        execution_time          TIMESTAMP WITH TIME ZONE    NOT NULL,
        picked                  BOOLEAN                     NOT NULL,
        picked_by               TEXT,
        last_success            TIMESTAMP WITH TIME ZONE,
        last_failure            TIMESTAMP WITH TIME ZONE,
        consecutive_failures    INT,
        last_heartbeat          TIMESTAMP WITH TIME ZONE,
        version                 BIGINT                      NOT NULL,

        PRIMARY KEY (task_name, task_instance)
    );

  03-create-outbox.sql: |
    -- Connect to testing_playground_service database and create outbox table
    \c testing_playground_service

    CREATE TABLE IF NOT EXISTS outbox_event (
      id              UUID PRIMARY KEY,
      reference_id    VARCHAR(255) NOT NULL,
      destination     VARCHAR(511) NOT NULL,
      payload_type    VARCHAR(511) NOT NULL,
      payload         BYTEA NOT NULL,
      status          VARCHAR(50) NOT NULL DEFAULT 'PENDING',
      created_at      TIMESTAMP NOT NULL DEFAULT now(),
      processed_at    TIMESTAMP,
      headers         jsonb,
      attempts        INT NOT NULL DEFAULT 0,
      next_attempt_at TIMESTAMP NOT NULL DEFAULT now(),
      fail_type       VARCHAR(32),
      fail_reason     TEXT
    );

    CREATE INDEX IF NOT EXISTS idx_outbox_event_status ON outbox_event(status);

  04-alter-outbox_event.sql: |
    -- Connect to testing_playground_service database and alter outbox_event table
    ALTER TABLE outbox_event ADD idempotence_key VARCHAR(511);


  05-create-shedlock.sql: |
    -- Connect to testing_playground_service database and create shedlock table
    \c testing_playground_service

    CREATE TABLE IF NOT EXISTS shedlock(
        name VARCHAR(64) NOT NULL,
        lock_until TIMESTAMP NOT NULL,
        locked_at TIMESTAMP NOT NULL,
        locked_by VARCHAR(255) NOT NULL,
        PRIMARY KEY (name)
    );
