apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: postgres
data:
  # Scripts run in alphabetical order when PostgreSQL first initializes
  # These scripts only execute on fresh database (empty data directory)
  # Add your own .sql files below following the naming pattern: 01-xxx.sql, 02-yyy.sql, etc.

  01-example-table.sql: |
    -- Example init script - creates a simple users table
    -- Modify this file to add your own database initialization scripts

    CREATE TABLE IF NOT EXISTS users (
      id              SERIAL PRIMARY KEY,
      username        VARCHAR(50) UNIQUE NOT NULL,
      email           VARCHAR(100) UNIQUE NOT NULL,
      created_at      TIMESTAMP NOT NULL DEFAULT now()
    );

    CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

    -- Insert sample data
    INSERT INTO users (username, email) VALUES
      ('admin', 'admin@example.com'),
      ('demo', 'demo@example.com')
    ON CONFLICT (username) DO NOTHING;
