apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-schema-registry-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: confluent-schema-registry
spec:
  project: default
  source:
    repoURL: git://host.docker.internal:9418/argocd-demo.git
    targetRevision: HEAD
    path: apps/confluent-schema-registry # This is the path to the Helm chart you just created
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka # Or the namespace where you want to deploy Schema Registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
