apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
  labels:
    app.kubernetes.io/name: kafka-ui
spec:
  project: default
  source:
    repoURL: https://provectus.github.io/kafka-ui-charts
    chart: kafka-ui
    targetRevision: 0.7.5
    helm:
      values: |
        yamlApplicationConfig:
          kafka:
            clusters:
              - name: my-cluster
                bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
                zookeeper: my-cluster-zookeeper-client.kafka:2181
          auth:
            type: disabled
          management:
            health:
              ldap:
                enabled: false

        service:
          type: NodePort
          port: 80
          nodePort: 30080

        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
