apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  labels:
    app.kubernetes.io/name: postgres
spec:
  project: default
  source:
    repoURL: git://host.docker.internal:9418/argocd-demo.git
    targetRevision: HEAD
    path: apps/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
