apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: _schemas
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    cleanup.policy: compact
    min.compaction.lag.ms: "0"
    delete.retention.ms: "86400000"
