apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: foo-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.ms: 86400000
    cleanup.policy: delete
